services:
  sonarr:
    ports:
      - 7788:7777
      - 8888:3333
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.example.com`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls.certresolver: myresolver
  radarr:
    ports:
      3333:3333